### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by Yavari** [delta-incubator/delta-dotnet#21]
Is this published to Nuget and what is the name of the Nuget package?

**Comment by mightyshazam** [comment]
The current nuget package is published [here](https://github.com/delta-incubator/delta-dotnet/pkgs/nuget/DeltaLake). It is only available via github packages, so that means you would need to use a `Nuget.config` file to specify the source.

**Comment by Yavari** [comment]
Is this how you mean?

I am getting the error shown the console.

![image](https://github.com/delta-incubator/delta-dotnet/assets/1221772/b6b1bcb5-1bfa-43ad-b8c3-ea9f251e2ee5)

**Comment by Yavari** [comment]
Did you add the correct link?

**Comment by mightyshazam** [comment]
Currently, the organization settings don't allow for making the nuget package public, so I'll look toward pushing something to nuget.

**Comment by diaconori** [comment]
Any update on this matter? @mightyshazam

**Comment by mightyshazam** [comment]
> Any update on this matter? @mightyshazam

We were looking at changing the API and implementation to incorporate [delta-kernel-rs](https://github.com/delta-incubator/delta-kernel-rs). We didn't want to publish a nuget package and then immediately publish a radically different one.

**Comment by mdrakiburrahman** [comment]
#78 should close this issue

**Comment by mightyshazam** [comment]
@Yavari @diaconori  The nuget package is finally published at [https://www.nuget.org/packages/DeltaLake.Net/0.1.0](https://www.nuget.org/packages/DeltaLake.Net/0.1.0).
The next step is to get it automated within the CI pipeline.
