### ISSUE TITLE
Urgent : Need help Reg : C# CRUD code to interact with delta lake and exception while trying out this project locally.

### ISSUE THREAD

**Issue by Dev4all365** [delta-incubator/delta-dotnet#35]
Hi @dennyglee , Hi @mightyshazam,

I am Chandan from Microsoft Hardware Health team. we are trying to interact with deltalake using C# for our project needs. so we are exploring this incubator project. our requirement was to create bare minimum prototype for :

1. Creating a delta lake table
2. Writing to delta lake table
3. Reading delta lake table
4. Deleting a record from a Delta Lake table

We tried out this project locally which generated deltalog and parquet files. 
<img width="652" alt="DeltaLakeoutput1" src="https://github.com/delta-incubator/delta-dotnet/assets/76824830/7779d3d9-37f4-49dd-8dc5-7946e666f5b6">

However we facing exception due some unreleased handle in Rust code :  May be C# Code is trying to release the handle of some resource, but the native Rust code may be still holding onto it, preventing the C# side from releasing it.

<img width="532" alt="Exception" src="https://github.com/delta-incubator/delta-dotnet/assets/76824830/f8f22525-5a59-4c0f-92bc-440c4b543b5f">

Please help take a look if possible for below points as we are blocked on this:

1. The resolution for above exception
2. Is there a possibility that The Parquet file generated as output of console application is not well formed --> Please comment
3. As this is pretty new code so please help add C# CRUD code  to interact with ADLS/cloud deltatables using C#

Thanks,
Chandan Kumar

**Comment by mightyshazam** [comment]
@Dev4all365 can you provide some minimal code to reproduce the issue or at least a stacktrace?

**Comment by Dev4all365** [comment]
Hi @mightyshazam, i am sharing Program.cs code file which i used and also stack trace file, exception started at Line:45 Program.cs. Thanks

[DeltaLake.zip](https://github.com/delta-incubator/delta-dotnet/files/15168276/DeltaLake.zip)
