### ISSUE TITLE
To avoid confusion on nuget packages

### ISSUE THREAD

**Issue by johnsusi** [delta-incubator/delta-dotnet#41]
Hi 👋

I can't believe that I missed this project when I recently started on my own implementation.

https://github.com/johnsusi/delta-net

with a nuget package published https://www.nuget.org/packages/DeltaLake/

My implementation is on top of ParquetSharp and implements the delta protocol directly in net instead of relying on delta-rs (due to some bugs in delta-rs on timestamps that I think now has been fixed)

If there is interest, I rather spend my energy contributing to this project than running my own.

**Comment by mightyshazam** [comment]
Help is welcome. Join the [delta users](https://go.delta.io/slack) slack workspace if you haven't already. We have a dotnet channel.
