### ISSUE TITLE
Connecting to Azure Data Lake Gen2 with Managed Identity

### ISSUE THREAD

**Issue by akulOn** [delta-incubator/delta-dotnet#76]
Hi,
I'm having some trouble connecting to Azure with Managed Identity.

I took a look at this PR in the delta-rs repo: https://github.com/delta-io/delta-rs/issues/600, but I can't get it to work.

I've tried using the az://<container>/<path> path, but no luck.

Environment.SetEnvironmentVariable("AZURE_STORAGE_ACCOUNT_NAME","templake");

string sourcePath = "abfss://temp@templake.dfs.core.windows.net/branches/people/";

using var runtime = new DeltaRuntime(RuntimeOptions.Default);
using var table = await DeltaTable.LoadAsync(
    runtime,
    sourcePath,
    new TableOptions(),
    CancellationToken.None);

foreach (var file in table.Files())
{
    Console.WriteLine(file);
}

**Comment by mdrakiburrahman** [comment]
I can take a look at this one

**Comment by MrPowers** [comment]
Thanks @mdrakiburrahman.  Assigned you this one!

**Comment by mdrakiburrahman** [comment]
PR is here: https://github.com/delta-incubator/delta-dotnet/pull/81
