### ISSUE TITLE
Make StorageOptions editable in TableOptions

### ISSUE THREAD

**Issue by akulOn** [delta-incubator/delta-dotnet#92]
Hi guys,

Thanks for adding the storage options!

I downloaded the latest package from nuget, but I can't set the StorageOptions in TableOptions on LoadAsync.
```
using DeltaLake.Runtime;
using DeltaLake.Table;
using Microsoft.AspNetCore.Mvc;

namespace DeltaTest.Controllers
{
    [Route("api/delta")]
    [ApiController]
    public class DeltaController : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var deltaRuntime = new DeltaRuntime(RuntimeOptions.Default);

            var deltaTable = await DeltaTable.LoadAsync(
                deltaRuntime,
                "abfss://test@testdatalake.dfs.core.windows.net/branches/people/",
                new TableOptions
                {
                    StorageOptions = new Dictionary<string, string>() <- **this is where I get the error**
                },
                CancellationToken.None);

            return Ok(deltaTable);
        }
    }
}
```

I noticed this in the TableOptions class

```
using System.Collections.Generic;

namespace DeltaLake.Table;

//
// Summary:
//     Options for creating a new delta table
public class TableOptions
{
    //
    // Summary:
    //     Optional version of the table to load
    public ulong? Version { get; set; }

    //
    // Summary:
    //     A map of string options
    public Dictionary<string, string> StorageOptions { get; } = new Dictionary<string, string>(); <- **could you add init/set here?**


    //
    // Summary:
    //     Whether or not to load files when building the table
    public bool WithoutFiles { get; set; }

    //
    // Summary:
    //     Buffer size for log files
    public uint? LogBufferSize { get; set; }
}
```

Could you make the StorageOptions editable on init in the TableOptions class?

**Comment by mightyshazam** [comment]
This is in the latest [main](https://github.com/delta-incubator/delta-dotnet/blob/6ecd720673fe3a19a9a8dd5c1142b33a7e7e9a1f/src/DeltaLake/Table/TableStorageOptions.cs). However, we haven't pushed a nuget package with the change. @mdrakiburrahman is working on a PR to add async functionality to his latest change. Then we will push out a new package with this change.
For now, the only option is pulling the code locally.

**Comment by akulOn** [comment]
Thanks for the quick response @mightyshazam! I'll pull the code locally and see how far I can get.

**Comment by mdrakiburrahman** [comment]
Hey gents, 

Just an update that I'm working on implementing the Nuget package for an app similar to [KDI](https://github.com/delta-io/kafka-delta-ingest) that works with Event Hub C# SDK and stresses this `delta-dotnet` package - I plan on finishing that work in the next 3-4 days.

From there, any lessons learned, and this issue:

https://github.com/delta-incubator/delta-dotnet/issues/91

Will be solved in a PR in the next few days.

**Comment by akulOn** [comment]
Hey guys,
I got the repo to work on my local machine, and everything is running as expected!

I noticed that the async functionality has been added, will the NuGet package be updated soon?

**Comment by mdrakiburrahman** [comment]
Glad to hear!

I believe @mightyshazam has this PR open with the latest changes:

https://github.com/delta-incubator/delta-dotnet/pull/88

Once it merges, you should have a new Nuget to download.
